name: Multi-Platform Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  android:
    name: Android Build
    if: false # ENABLE_ANDROID: Set to true to enable hardware allocation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.7'
      - run: flutter pub get
      - run: flutter build apk --release

  ios:
    name: iOS Build
    if: false # ENABLE_IOS: Set to true to enable hardware allocation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.7'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

  web:
    name: Web Build
    if: false # ENABLE_WEB: Set to true to enable hardware allocation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.7'
      - run: flutter pub get
      - run: flutter build web --release

  windows:
    name: Windows Build
    if: false # ENABLE_WINDOWS: Set to true to enable hardware allocation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.7'
      - run: flutter pub get
      - run: flutter build windows --release

  macos:
    name: macOS Build
    if: false # ENABLE_MACOS: Set to true to enable hardware allocation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.7'
      - run: flutter pub get
      - run: flutter build macos --release

  linux:
    name: Linux Build
    if: false # ENABLE_LINUX: Set to true to enable hardware allocation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.7'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter pub get
          flutter build linux --release
